apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume
  labels:
    type: local
# For real production setups, we don´t mount to one node and use a proper cloud storage endpoint
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"